### ISSUE TITLE
how to run the program after building

### ISSUE THREAD

**Issue by victorswan** [IRCAD/sight#7]
after building the whole source code without errors then  I got lots of .bat file. but when I run the .bat file. it can not be run. how to run

**Comment by schweitzer** [comment]
Hello @victorswan 

Thanks for using sight.

We will need more details to help you.

What do you mean by "it can not be run" ? Have you any errors ? What application did you tried ?

Please also give us your version of windows and Visual Studio.

**Comment by victorswan** [comment]
when I run dicomxplorer.bat. It reports "sightrun.exe is not a command or a program can be run"
I use Visual Studio 2019 on Windows 10

**Comment by mkugker** [comment]
Hello. 

We are deeply sorry for the delay of the answer.
Can you confirm that you didn't move your dicomxplorer.bat after its generation? 
Can you specify if you run the application from your build or from the install folder? 
Can you confirm that you have a sightrun.exe in the same folder as your dicomxplorer.bat? 

Best regards,

**Comment by schweitzer** [comment]
No update since a while, I'm closing the issue.

Feel free to re-open it if needed.
